name: main
on: [push]
jobs:
  run:
    name: run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
    - uses: actions/checkout@master

    - name: setup-node
      uses: actions/setup-node@master
      with:
        version: 12.x

    - name: yarn
      run: yarn

    - name: format
      run: yarn format

    - name: lint
      run: yarn lint

    - name: deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: dist
        BUILD_SCRIPT: yarn build
